### ISSUE TITLE
Optimize extractControls

### ISSUE THREAD

**Issue by Eeems** [geekbozu/NintendoWiSpy#10]
Instead of declaring `ret` as an empty object, and then initializing it's properties I would suggest doing the following:
```javascript
var button = {},
    analog = {};
// Code here
return {
    button: button,
    analog: analog
};
```
This way you can also shorted up the rest of your code instead of having to use `ret.button.` or `ret.analog.`
I've updated my older optimization snippet to include this concept (https://www.irccloud.com/pastebin/zvPElZLJ/).

**Comment by geekbozu** [comment]
See #11
