### ISSUE TITLE
Make sure all JavaScript variables are declared. 

### ISSUE THREAD

**Issue by Eeems** [geekbozu/NintendoWiSpy#8]

**Comment by geekbozu** [comment]
Could you check this again. I think its much better

**Comment by Eeems** [comment]
Why do you have a ton of lines that only contain `;`?

**Comment by Eeems** [comment]
I would also suggest merging var statements eg:
```
var i = 0,
    j = 1;
```

**Comment by geekbozu** [comment]
If that is in ReconectingSockets.js thats a third party library I'm importing for some future functionality reasons instead of including as a dependency. It also means I would rather not edit it if I don't have to :D

**Comment by Eeems** [comment]
I would suggest moving all of your code inside a closure and only adding things to the global scope you explicitly want there. ie:
```javascript
(function(){
    // Your code here
   window.globalValue = internalValue;
})();
```

**Comment by geekbozu** [comment]
Do i need to call this or just wrap my whole fine in that essentially?

**Comment by Eeems** [comment]
Just wrap your whole file. It's self calling. It's basically doing this: `(exp)()`

**Comment by geekbozu** [comment]
Done :D
